on: pull_request
name: 'On PR '
jobs:
  build-pre-commit-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build pre-commit image
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build pre-commit

