on: pull_request
name: 'On PR '
jobs:
  build-pre-commit-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build pre-commit image
      run:  docker build pre-commit
