on: pull_request
name: 'On PR '
jobs:
  build-pre-commit-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: filter-to-pr-open-synced
      uses: actions/bin/filter@master
      with:
        args: action 'opened|synchronize'
    - name: build pre-commit image
      run: docker build pre-commit
